name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        venv/bin/pip install -r requirements.txt
        venv/bin/pip install pytest  # Install pytest
    
    - name: Set up Chrome and ChromeDriver
      uses: SeleniumHQ/setup-selenium@v2

    - name: Run tests
      run: |
        venv/bin/pytest pythonProject/day1  # Adjust the path as needed
